### ISSUE TITLE
Ask: Django 4.2 support and aldryn-forms dependency

### ISSUE THREAD

**Issue by joshyu** [django-cms/djangocms-moderation#257]
Hi team,

I found that **djangocms-moderation** depends on **aldryn-forms** which hasn't been supported by divio any more.
If we want to upgrade this addon to django 4.2 compatible, we also need to make aldryn-forms django 4.2 compatible.

How do you plan to achieve this?

**Comment by fsbraun** [comment]
@Aiky30 started some work recently in #256. A likely scenario is that the aldryn-forms dependency will be dropped.

**Comment by joshyu** [comment]
Hi @fsbraun ,

Right now we need to add django4.2 support and work with django-cms 4.0.1.x.
Can you please help to create a branch **support/django-cms-4.0.x** based on version 2.1.6 ?
Thanks.

**Comment by fsbraun** [comment]
@joshyu What exactly are you referring to with "version 2.1.6"?

**Comment by joshyu** [comment]
@fsbraun,

the latest released version which is compatible with django-cms 4.0.1.x branch is 2.1.6, so please create a branch **support/django-cms-4.0.x**  based on tag 2.1.6(https://github.com/django-cms/djangocms-moderation/tree/2.1.6) 

then we can continue supporting django-cms 4.0.1.x and django 4.2 .

**Comment by fsbraun** [comment]
Hi @joshyu, 

ok, now I got it. That makes sense, once there are changes introduced at any point that will not allow running moderation on django CMS 4.0. For now, I do not see the need and would advise against it to avoid the code bases drifting apart for no reason. If you think differently, you can create that branch yourself.

Generally speaking: is it not much easier to move on to django CMS 4.1 and avoid reinventing everything again? Wouldn't that save quite some resources?

**Comment by joshyu** [comment]
Hi @fsbraun ,

As currently we have no much effort to do CMS upgrade, and there are some other changes due to versioning upgrade.
The leaders want to do it later.

Can you help me create this branch in current repo? I don't have the permission to do that.
Thanks.

**Comment by fsbraun** [comment]
ok, but let's give it a meaningful name, like `support/moderation-forms` which is the bit that depends on aldryn-forms and probably will go away in the main branch when we add django 4.2 support. Are you sure you are using the module `djangocms_moderation.contrib.moderation_forms`?

**Comment by joshyu** [comment]
Hi @fsbraun ,
I would better name this branch **support/django-cms-4.0.x** because this branch mainly focus on support django cms 4.0.1.x version. Meanwhile, we can follow what Andrew did to remove **aldryn-forms** .

**Comment by fsbraun** [comment]
Superb! Let us keep the django CMS 4.0 compatibility here.
