### ISSUE TITLE
[BUG] Workflow admin view is breaking. SortableAdmin is not working as expected

### ISSUE THREAD

**Issue by vipulnarang95** [django-cms/djangocms-moderation#268]
## Description
Workflow admin view is breaking. SortableAdmin is not working as expected
Name and link to open workflow admin form is empty
https://github.com/django-cms/djangocms-moderation/blob/master/djangocms_moderation/admin.py#L1014

## Steps to reproduce
Go to django admin --> Moderations --> workflows
click on Workflow and it is not displaying the name to open to workflow form

## Do you want to help fix this issue?

* [x] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome.
* [ ] No, I only want to report the issue.

**Comment by joshyu** [comment]
Screen shot: 
workflow list: 
![image](https://github.com/django-cms/djangocms-moderation/assets/100244/51d6f784-ac8a-4da3-875c-030af40d3ff3)
workflow editing:
![image](https://github.com/django-cms/djangocms-moderation/assets/100244/c36c8318-73fb-421f-8124-b9668650a481)

Hi @fsbraun ,
This is related to our latest PR for django 4.2 :(https://github.com/django-cms/djangocms-moderation/commit/fd77632e3c256d4aeba99903c57380d8a246f7cf#diff-9aa20565b718f5d1eac42d9067728bbd92c65bed2ad188f22224ca23552623d5) 

![image](https://github.com/django-cms/djangocms-moderation/assets/100244/49015d77-35e3-4f4e-931d-9351da61eca3)

If we don't add this parental class, we will get the error:
<img width="1147" alt="image" src="https://github.com/django-cms/djangocms-moderation/assets/100244/bb530bf5-38e3-423c-b74e-24420a8574b7">

**Comment by vipulnarang95** [comment]
Also removing the SortableInlineAdminMixin from WorkflowStepInline loads the admin view correctly in line https://github.com/django-cms/djangocms-moderation/blob/master/djangocms_moderation/admin.py#L1003

**Comment by fsbraun** [comment]
This comment might support your finding @vipulnarang95: https://django-admin-sortable2.readthedocs.io/en/latest/installation.html#upgrading-from-version-1

* Remove `SortableInlineAdminMixin` from `WorkflowStepInline`
* Ensure it is added to all admin classes using `WorkflowStepInline`, such as `WorkflowAdmin`

@joshyu Can you confirm @vipulnarang95's finding?

**Comment by joshyu** [comment]
@fsbraun ,
I removed both `SortableAdminMixin` and `SortableInlineAdminMixin` from inline admin and its parent class, It seems that the list rendered correctly, but I got an error while saving a new workflow, as below screenshot:

![image](https://github.com/django-cms/djangocms-moderation/assets/100244/db7e5fee-cf1a-4d89-916d-23257c4dca07)

**Comment by vipulnarang95** [comment]
We need to modify forms at https://github.com/django-cms/djangocms-moderation/blob/master/djangocms_moderation/forms.py#L26
It would work fine then

**Comment by joshyu** [comment]
> We need to modify forms at https://github.com/django-cms/djangocms-moderation/blob/master/djangocms_moderation/forms.py#L26 It would work fine then

@vipulnarang95 , how to update this form? Can you share more detail?

**Comment by joshyu** [comment]
@fsbraun,

I found that the error I mentioned was ever mentioned by Sergi of What.digital and he raised a PR for it.https://github.com/jrief/django-admin-sortable2/pull/371

**Comment by joshyu** [comment]
Hi @fsbraun / @vipulnarang95, 

From my understanding, the sorting functionality might be in the requirements list, so I think it's not a best solution only to remove the dependencies of `django-admin-sortable2`. 

Whether can we create a new branch `without/adminsortable` based on master branch, this temporary solution to remove the dependency of `adminsortable2` will be put there. 

How do you think?

**Comment by vipulnarang95** [comment]
From the authoring perspective this functionality of Sort is available just drag and drop feature is not available. If the problem is there in the dependent addon and for our release target we can get a dev release and fix it in later stage as this is not a blocker and the feature is also not used at all.
@fsbraun please suggest the best possible way to deliver this.

**Comment by fsbraun** [comment]
I'd appreciate if we could keep the drag-and-drop sorting capability. 

@jrief Can you give https://github.com/jrief/django-admin-sortable2/pull/371 a second look? 

@vipulnarang95 @joshyu Is there a way of making a `default_order_field` not `None` in djangocms-moderation? And would this also fix the issue?

**Comment by vipulnarang95** [comment]
@fsbraun I checked and used this change in django admin sortable2 in my local and it still doesn't resolves the issue. The issue still exists

Also the getattr error josh mentioned was coming after removing the SortableAdmin and SortableAdminMixin class.
I am debugging django admin sortable2 now and will share my findings.

**Comment by FreemanPancake** [comment]
> I'd appreciate if we could keep the drag-and-drop sorting capability.
> 
> @jrief Can you give [jrief/django-admin-sortable2#371](https://github.com/jrief/django-admin-sortable2/pull/371) a second look?
> 
> @vipulnarang95 @joshyu Is there a way of making a `default_order_field` not `None` in djangocms-moderation? And would this also fix the issue?

Hi @fsbraun ,
This was not a issue for `default_order_field`, as there is a init method called _get_default_ordering(), this will return and set the `default_order_field` and `default_order_direction` 's value as 'name'.
The problem was on the `get_list_display()` method they just replace the `name` column with `_reorder_`, which I believe should be append to the original `list_display` list. 

<img width="1524" alt="image" src="https://github.com/django-cms/djangocms-moderation/assets/19234409/4a2bb394-d91b-4552-a6f1-8d6230644389">

And I believe we should add attribute `enable_sorting` to desired Admin  and set its value as `True` if we want to enable sorting function or  `False` if we don't need this.

**Comment by fsbraun** [comment]
@vipulnarang95 Did https://github.com/jrief/django-admin-sortable2/pull/404 solve this problem?

**Comment by fsbraun** [comment]
Solved by https://github.com/jrief/django-admin-sortable2/pull/404
