### ISSUE TITLE
[BUG] Create workflow encounter error, with djangocms-quickstart project

### ISSUE THREAD

**Issue by FreemanPancake** [django-cms/djangocms-moderation#277]
## Description
I try to install djangocms-moderation into django-cms-quickstart project: https://github.com/django-cms/django-cms-quickstart
to test out the versioning management and workflow. but below error popped up when create new workflow:
<img width="793" alt="image" src="https://github.com/user-attachments/assets/f62e4206-e84a-4d87-8412-6f457218bb2c">

## Steps to reproduce

1. follow the steps on django-cms-quickstart homepage to setup the project
2. modify the requirement.in and requirement.txt file and settings file to install and include the djangocms-moderation package
<img width="1223" alt="image" src="https://github.com/user-attachments/assets/baf39a4a-9353-49d3-8527-85ccd4e7de5a">
<img width="1183" alt="image" src="https://github.com/user-attachments/assets/86ebe24c-f3b2-4f77-bc1b-28088c8f9bd9">
<img width="1188" alt="image" src="https://github.com/user-attachments/assets/580a3931-49df-44df-b381-92940f2c190f">
<img width="1178" alt="image" src="https://github.com/user-attachments/assets/30bd8314-5274-4954-ab22-529c2d9c0b4e">
4. Then go to admin panel, create new page content.
5. go through the workflow creation process to create new workflow then you will find out the error

## Expected behaviour
Workflow creates normally

## Actual behaviour
encounter error

## Additional information (CMS/Python/Django versions)

Django 4.2
Python 3.11
Django-CMS 4.1.2

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome.
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
@FreemanPancake Can you share the traceback?

**Comment by fsbraun** [comment]
Thanks, that's already helpful. Can you let me know the local variables of line 259 in `admin.py` (the first highlighted row)?

**Comment by fsbraun** [comment]
@FreemanPancake Can you check if the error goes away with `django-admin-sortable2==2.2.2`?

**Comment by joshyu** [comment]
Hi @fsbraun ,

After installing the fix you mentioned above, the error disappeared, but we got another error as below.
I am also checking how to fix it, and wait for your input.

![image](https://github.com/user-attachments/assets/6dee768d-87bf-42b0-8e82-e35588e46066)

**Comment by joshyu** [comment]
Hi @fsbraun ,
I have a question about below line, in `Workflow` model, the default_order field is `name`, which is a charfield. If we specify the `output_field` as Integer,  I think it might be a mismatch.

![image](https://github.com/user-attachments/assets/2bd6a41e-28df-411f-af8d-548ff995528a)

**Comment by fsbraun** [comment]
@joshyu I think your analysis is correct: If you want a sortable admin, you need an integer-type field for sorting. This means either: 
* Add a `position = models.PositiveIntegerField(...)` field to `Workflow` which then needs to be the primary ordering field, or,
* remove `SortableAdminMixin` form `WorkflowAdmin`

**Comment by joshyu** [comment]
@fsbraun ,
Sorry I was blocked with another high priority requirement. I will ask @FreemanPancake  to check it and feedback to you later.

**Comment by FreemanPancake** [comment]
Hi @joshyu and @fsbraun ,
I have installed this fix version on django-cms-quickstart project, and it worked.
Thank you all for the outcome.

**Comment by fsbraun** [comment]
@FreemanPancake That's great news! I think we're approaching a level of stability where we can publish moderation on pypi.

**Comment by fsbraun** [comment]
fixed by #279
